# Generated by Django 3.0.6 on 2020-05-17 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_pharmacy_products'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('automatically_created', models.BooleanField(default=False)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pharmacies.Pharmacy')),
            ],
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
