# Generated by Django 3.0.6 on 2020-05-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('center_code', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_num', models.CharField(max_length=255)),
                ('areas', models.CharField(max_length=255)),
                ('provinces', models.CharField(max_length=255)),
                ('regions_ccaa', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('geometry_lat', models.CharField(max_length=255)),
                ('geometry_lng', models.CharField(max_length=255)),
            ],
        ),
    ]
