# Generated by Django 3.0.6 on 2020-05-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
